export const constants = {
    'URL_POST_LOGIN': '/login',
    "URL_REGISTER": '/register',
    'URL_USER': '/user',
    'URL_USER_NAME': '/user/name',
    'URL_FILE': '/file',
    'URL_GET_DIRECTORY': '/directory',
    'URL_GET_CHILD_DIRECTORY': '/directory/:id/children',
    'URL_GET_FILES_BY_DIRECTORY': '/directory/:id/files',
    'URL_GET_FILES_BY_VERSION': '/file/:name/versions',
    'URL_GET_FILE_BY_VERSION': '/file/version/:name/:number',
    'URL_DOWNLOAD': '/download',
    'URL_GET_HISTORY_BY_FILE': '/history/file/:id',
    'URL_LINK_FILE': '/link/file/:id',
    'URL_LINK_DIR': '/link/dir/:id',
};
