export const constants = {
    'URL_POST_LOGIN': '/login',
    "URL_REGISTER": '/register',
    'URL_USER': '/user',
    'URL_USER_ISADMIN': '/user/isAdmin',
    'URL_USER_NAME': '/user/name',
    'URL_USER_BY_ID': '/user/id',
    'URL_FILE': '/file',
    'URL_DIRECTORY': '/directory',
    'URL_DIRECTORY_IS_DELETED': '/directory/:id/isDeleted',
    'URL_GET_CHILD_DIRECTORY': '/directory/:id/children',
    'URL_GET_DELETED_DIRECTORY': '/directory/:id/deletedChildren',
    'URL_GET_FILES_BY_DIRECTORY': '/directory/:id/files',
    'URL_DOWNLOAD_DIR': '/download/folder',
    'URL_GET_DELETED_FILES': '/directory/:id/deletedFiles',
    'URL_HISTORY': '/history',
    'URL_HISTORY_BY_DIR': '/directory/:id/histories',
    'URL_GET_FILES_BY_VERSION': '/file/:name/:directory/versions',
    'URL_GET_FILE_BY_VERSION': '/file/version/:name/:directory/:number',
    'URL_DOWNLOAD': '/download',
    'URL_GET_HISTORY_BY_FILE': '/history/file/:id',
    'URL_LINK_FILE': '/link/file/:id',
    'URL_LINK_DIR': '/link/dir/:id',
    'URL_LINK': '/link',
    'URL_ACTIVE_SUBSCRIPTION' : '/subscription/active',
    'URL_SUBSCRIPTION' : '/subscription',
    'URL_CURRENT_TRANSACTION' : '/transaction/current',
    'URL_TRANSACTION' : '/transaction'
};
